Repository iden3/iden3js, pull requests merged in 2019-01, with the labels that each got.

#30 update mimc7 seed, update claim structure
  src/claim/assign-name/assign-name.js
  src/claim/assign-name/assign-name.test.js
  src/claim/authorize-ksign/authorize-ksign.js
  src/claim/authorize-ksign/authorize-ksign.test.js
  src/claim/basic/basic.js
  src/claim/basic/basic.test.js
  src/claim/entry/entry.js
  src/claim/entry/entry.test.js
  src/claim/set-root-key/set-root-key.js
  src/claim/set-root-key/set-root-key.test.js
  src/constants.js
  src/sparse-merkle-tree/mimc7.js
  src/sparse-merkle-tree/sparse-merkle-tree.js
  src/sparse-merkle-tree/sparse-merkle-tree.test.js
  src/utils.js
Labels: enhancement

#35 Add calculate counterfactual identity address
  src/eth/counterfactual.js
  src/eth/counterfactual.test.js
  src/eth/testbytecode.json
  src/index.js
  test/id.test.js
Labels: buidl

#41 Feature/login protocol
  README.md
  package.json
  src/claim/assign-name/assign-name.js
  src/claim/assign-name/assign-name.test.js
  src/claim/claim-utils.test.js
  src/claim/entry/entry.test.js
  src/index.js
  src/key-container/local-storage-container.js
  src/protocols/README.md
  src/protocols/login.js
  src/protocols/login.test.js
  src/protocols/nonceDB.js
  src/protocols/nonceDB.test.js
  src/protocols/proofs.js
  src/protocols/protocols.js
  src/sparse-merkle-tree/mimc7.js
  src/utils.test.js
  test/protocols-login.test.js
  test/relay.test.js
Labels: buidl

#47 Add smtUtils.importClaimsDump to import merkletree generated in go-iden3
  package.json
  src/index.js
  src/sparse-merkle-tree/sparse-merkle-tree-utils.js
  src/sparse-merkle-tree/sparse-merkle-tree-utils.test.js
Labels: buidl

#48 fix login protocol pubK instead of addr for the ksign
  src/protocols/login.js
  src/protocols/login.test.js
  test/protocols-login.test.js
Labels: bug, buidl

#46 Add login spec documentation
  src/protocols/README.md
  src/protocols/login_flow.png
  src/protocols/login_overview.png
  src/protocols/login_spec.md
  src/protocols/login_spec_rationale.md
Labels: buidl
