Repository iden3/iden3js, pull requests merged in 2019-02, with the labels that each got.

#54 Fix ALL eslint errors, add eslint to travis
  .travis.yml
  package.json
  src/admin/requests.js
  src/auth/dapp.js
  src/claim/assign-name/assign-name.js
  src/claim/authorize-ksign-secp256k1/authorize-ksign-secp256k1.js
  src/claim/authorize-ksign/authorize-ksign.js
  src/claim/basic/basic.js
  src/claim/claim-utils.test.js
  src/claim/entry/entry.js
  src/claim/entry/entry.test.js
  src/claim/set-root-key/set-root-key.js
  src/eth/counterfactual.js
  src/eth/counterfactual.test.js
  src/http/private-folder.js
  src/http/relay.debug.js
  src/http/relay.js
  src/protocols/login.js
  src/protocols/login.test.js
  src/protocols/proofs.js
  src/sparse-merkle-tree/mimc7.js
  src/sparse-merkle-tree/sparse-merkle-tree-utils.js
  src/sparse-merkle-tree/sparse-merkle-tree-utils.test.js
  src/utils.test.js
Labels: enhancement

#60 Update naming consensus interaction with go-iden3
  src/claim/claim.js
  src/http/relay-debug.js
  src/http/relay.js
  src/id/id.js
  src/protocols/login.js
  src/protocols/login.test.js
  src/protocols/proofs.js
  test/id.test.js
  test/protocols-login.test.js
Labels: buidl

#62 publish only necessary files. Clear localStorage when importing wallet
  index.js
  package.json
  src/auth/auth.js
  src/db/db.js
  src/utils.test.js
Labels: buidl

#69 Generalize IdenAssertV01 code
  src/protocols/login.js
  src/protocols/login.test.js
  test/protocols-login.test.js
Labels: enhancement

#75 fixed npm run browserify
  package.json
Labels: bug, buidl
