Repository iden3/iden3js, pull requests merged in 2019-09, with the labels that each got.

#130 Feature/migrate poseidon
  package.json
  src/canary.test.js
  src/claim/claim-authorize-ksign-babyjub.test.js
  src/claim/entry.js
  src/crypto/babyjub-utils.test.js
  src/crypto/crypto.js
  src/crypto/eddsa-babyjub.test.js
  src/crypto/mimc7.js
  src/crypto/poseidon.js
  src/identity/identity-utils.test.js
  src/identity/identity.test.js
  src/key-container/kc-utils.js
  src/key-container/kc-utils.test.js
  src/key-container/key-container.js
  src/protocols/login.test.js
  src/sparse-merkle-tree/mimc7.js
  src/sparse-merkle-tree/sparse-merkle-tree.js
  src/sparse-merkle-tree/sparse-merkle-tree.test.js
  src/utils.js
Labels: buidl

#131 Add poseidon sign/verify in eddsa
  .travis.yml
  src/crypto/eddsa-babyjub.js
Labels: buidl

#132 migrate from mimc7 to poseidon
  src/canary.test.js
  src/claim/claim-assign-name.test.js
  src/claim/claim-authorize-eth-key.test.js
  src/claim/claim-authorize-ksign-babyjub.test.js
  src/claim/claim-authorize-ksign-secp256k1.test.js
  src/claim/claim-basic.test.js
  src/claim/claim-link-object-identity.test.js
  src/claim/claim-set-root-key.test.js
  src/claim/entry.js
  src/claim/entry.test.js
  src/crypto/mimc7.js
  src/crypto/poseidon.js
  src/id/id-utils.test.js
  src/identity/identity-utils.test.js
  src/identity/identity.test.js
  src/key-container/kc-utils.js
  src/key-container/key-container.js
  src/protocols/login.test.js
  src/sparse-merkle-tree/sparse-merkle-tree-utils.test.js
  src/sparse-merkle-tree/sparse-merkle-tree.js
  src/sparse-merkle-tree/sparse-merkle-tree.test.js
  src/utils.js
Labels: buidl

#133 fix smt poseidon call for leafs, update id type BJP0. SMT test vector…
  src/canary.test.js
  src/id/id-utils.test.js
  src/identity/identity-utils.js
  src/identity/identity-utils.test.js
  src/identity/identity.test.js
  src/sparse-merkle-tree/sparse-merkle-tree-utils.test.js
  src/sparse-merkle-tree/sparse-merkle-tree.js
  src/sparse-merkle-tree/sparse-merkle-tree.test.js
Labels: bug, buidl

#134 fix max levels reached
  src/sparse-merkle-tree/sparse-merkle-tree.js
  src/sparse-merkle-tree/sparse-merkle-tree.test.js
Labels: bug
